### ISSUE TITLE
Compilation issue on windows with std::to_string

### ISSUE THREAD

**Issue by christopho** [christopho/solarus#651]
The current master does not compile on with gcc:

    j:/Solarus-game/Engine/src/SpriteData.cpp: In member function 'const Solarus::SpriteAnimationDirectionData& Solarus::SpriteAnimationData::get_direction(int) const':
    j:/Solarus-game/Engine/src/SpriteData.cpp:297:42: error: 'to_string' is not a member of 'std' 
    std::string("No such direction: ") + std::to_string(direction_nb)); 

This might be due to the flag -std=gnu++11, used on windows to avoid a compilation error in vorbisfile.h with fseeko64

**Comment by Morwenn** [comment]
Which version of GCC? I currently compile on Windows with GCC 4.9 -std=c++11 and I never encountered this error. But I am using MinGW-w64 (32 bits); it seems that the error is known and have been fixed in MinGW-w64: http://stackoverflow.com/q/12975341/1364752

It is possible that this error has never been fixed in the regular release of MinGW.

**Comment by christopho** [comment]
It's @Renkineko who has the problem, he will tell us the gcc version as soon as possible.

**Comment by minirop** [comment]
it's a [bug in mingw/gcc](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52015) caused by a broken vswprintf. Some are affected, some aren't. it's at least until 4.8.1 AFAIK.

**Comment by Renkineko** [comment]
I'm using gcc 4.8.1 :)

**Comment by christopho** [comment]
I have the same issue with 4.8.1.
